#spring:
#  application:
#    name: etl-kettle
##  profiles:
##    active: dev #默认为开发环境
#
#server:
#  port: 10001
#  servlet:
#    context-path: /
#    session:
#      timeout: 300
#
#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#logging:
#  level:
#    root: info #日志配置DEBUG,INFO,WARN,ERROR
#    com.caixin.data.middle.etl.kettle.admin: debug
##  file: demo_log.log #配置日志生成路径
##  path: /var/logs #配置日志文件名称
#
#
#spring:
#  datasource:
#    ds1:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://106.12.160.245:3306/web_kettle?serverTimezone=Asia/Shanghai&useFastDateParsing=false&characterEncoding=UTF-8&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
#      username: root
#      password: 123456
#      druid:
#        initial-size: 5 #连接池初始化大小
#        min-idle: 10 #最小空闲连接数
#        max-active: 20 #最大连接数
#        web-stat-filter:
#          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#        stat-view-servlet: #访问监控网页的登录用户名和密码
#          login-username: druid
#          login-password: druid
#
#  ds2:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://106.12.160.245:3306/web_kettle?serverTimezone=Asia/Shanghai&useFastDateParsing=false&characterEncoding=UTF-8&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
#      username: root
#      password: 123456
#      druid:
#        initial-size: 5 #连接池初始化大小
#        min-idle: 10 #最小空闲连接数
#        max-active: 20 #最大连接数
#        web-stat-filter:
#          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#        stat-view-servlet: #访问监控网页的登录用户名和密码
#          login-username: druid
#          login-password: druid


####################################
#spring:
#  application:
#    name: etl-kettle
#
#server:
#  port: 10001
#  servlet:
#    context-path: /
#    session:
#      timeout: 300
#
#datasource:
#  ds1:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://localhost:3306/kettle?serverTimezone=Asia/Shanghai&useFastDateParsing=false&characterEncoding=UTF-8&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
#    username: root
#    password: 123456
#    druid:
#      initial-size: 5 #连接池初始化大小
#      min-idle: 10 #最小空闲连接数
#      max-active: 20 #最大连接数
#      web-stat-filter:
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#      stat-view-servlet: #访问监控网页的登录用户名和密码
#        login-username: druid
#        login-password: druid
#
#  ds2:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://localhost:3306/kettle?serverTimezone=Asia/Shanghai&useFastDateParsing=false&characterEncoding=UTF-8&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
#    username: root
#    password: 123456
#    druid:
#      initial-size: 5 #连接池初始化大小
#      min-idle: 10 #最小空闲连接数
#      max-active: 20 #最大连接数
#      web-stat-filter:
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#      stat-view-servlet: #访问监控网页的登录用户名和密码
#        login-username: druid
#        login-password: druid
#
#mybatis:
#  mapper-locations:
#    - classpath:mappings/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#logging:
#  level:
#    root: info #日志配置DEBUG,INFO,WARN,ERROR
#    com.caixin.data.middle.etl.kettle.admin: debug
##  file: demo_log.log #配置日志生成路径
##  path: /var/logs #配置日志文件名称
